In [72]:
import pandas as pd

import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

FLIGHTS_PKL_PATH = os.environ.get("FLIGHTS_PKL_PATH")

In [80]:
df = pd.read_pickle(FLIGHTS_PKL_PATH)

In [81]:
df.shape

(246, 11)

In [86]:
df = df[df['destination']=='GOT']

In [87]:
display(df.head())

,origin,destination,outbound_depart,outbound_arrive,outbound_duration,inbound_depart,inbound_arrive,inbound_duration,total_amount,airline,trip_days
208,WAW,GOT,2023-10-02 18:30:00,2023-10-02 23:00:00,0 days 02:45:00,2023-10-04 06:20:00,2023-10-04 09:20:00,0 days 02:05:00,333.73,SAS,1
209,WAW,GOT,2023-10-02 18:30:00,2023-10-02 23:00:00,0 days 02:45:00,2023-10-05 08:30:00,2023-10-05 17:50:00,0 days 02:45:00,367.42,SAS,2
210,WAW,GOT,2023-10-02 18:05:00,2023-10-02 22:40:00,0 days 03:45:00,2023-10-06 12:00:00,2023-10-06 17:15:00,0 days 03:30:00,210.01,Brussels Airlines,3
211,WAW,GOT,2023-10-02 18:30:00,2023-10-02 23:00:00,0 days 02:45:00,2023-10-07 06:20:00,2023-10-07 13:05:00,0 days 02:05:00,333.73,SAS,4
212,WAW,GOT,2023-10-02 18:30:00,2023-10-02 23:00:00,0 days 02:45:00,2023-10-04 06:20:00,2023-10-04 09:20:00,0 days 02:05:00,333.73,SAS,1

In [88]:
df2 = df[df['outbound_depart'] > '2023-10-08']
df2.sort_values(['total_amount', 'outbound_depart', 'trip_days'], ascending=[True, True, True]).head(50)

,origin,destination,outbound_depart,outbound_arrive,outbound_duration,inbound_depart,inbound_arrive,inbound_duration,total_amount,airline,trip_days
230,WAW,GOT,2023-10-08 18:05:00,2023-10-08 22:40:00,0 days 03:45:00,2023-10-12 12:00:00,2023-10-12 17:15:00,0 days 03:30:00,210.01,Brussels Airlines,3
231,WAW,GOT,2023-10-08 18:05:00,2023-10-08 22:40:00,0 days 03:45:00,2023-10-13 12:00:00,2023-10-13 17:15:00,0 days 03:30:00,210.01,Brussels Airlines,4
237,WAW,GOT,2023-10-10 18:05:00,2023-10-10 22:40:00,0 days 03:45:00,2023-10-15 18:20:00,2023-10-15 22:45:00,0 days 03:30:00,210.01,Brussels Airlines,5
242,WAW,GOT,2023-10-13 06:50:00,2023-10-13 11:15:00,0 days 03:40:00,2023-10-15 18:20:00,2023-10-15 22:45:00,0 days 03:30:00,210.01,Brussels Airlines,2
245,WAW,GOT,2023-10-14 06:50:00,2023-10-14 11:15:00,0 days 03:40:00,2023-10-18 12:00:00,2023-10-18 17:15:00,0 days 03:30:00,210.01,Brussels Airlines,4
243,WAW,GOT,2023-10-13 20:35:00,2023-10-13 22:20:00,0 days 01:45:00,2023-10-17 08:00:00,2023-10-17 09:40:00,0 days 01:40:00,238.08,LOT Polish Airlines,3
240,WAW,GOT,2023-10-12 20:35:00,2023-10-12 22:20:00,0 days 01:45:00,2023-10-14 08:00:00,2023-10-14 09:40:00,0 days 01:40:00,253.12,LOT Polish Airlines,1
241,WAW,GOT,2023-10-12 20:35:00,2023-10-12 22:20:00,0 days 01:45:00,2023-10-17 08:00:00,2023-10-17 09:40:00,0 days 01:40:00,253.12,LOT Polish Airlines,4
236,WAW,GOT,2023-10-10 20:35:00,2023-10-10 22:20:00,0 days 01:45:00,2023-10-14 08:00:00,2023-10-14 09:40:00,0 days 01:40:00,271.17,LOT Polish Airlines,3
239,WAW,GOT,2023-10-11 18:30:00,2023-10-11 23:00:00,0 days 02:45:00,2023-10-15 09:25:00,2023-10-15 17:50:00,0 days 02:35:00,299.44,SAS,3
229,WAW,GOT,2023-10-08 20:35:00,2023-10-08 22:20:00,0 days 01:45:00,2023-10-10 08:00:00,2023-10-10 09:40:00,0 days 01:40:00,316.29,LOT Polish Airlines,1
232,WAW,GOT,2023-10-09 20:35:00,2023-10-09 22:20:00,0 days 01:45:00,2023-10-11 08:00:00,2023-10-11 09:40:00,0 days 01:40:00,316.29,LOT Polish Airlines,1
234,WAW,GOT,2023-10-10 20:35:00,2023-10-10 22:20:00,0 days 01:45:00,2023-10-12 08:00:00,2023-10-12 09:40:00,0 days 01:40:00,316.29,LOT Polish Airlines,1
244,WAW,GOT,2023-10-14 13:40:00,2023-10-15 09:00:00,0 days 02:15:00,2023-10-17 09:45:00,2023-10-17 17:50:00,0 days 02:40:00,333.73,SAS,3
233,WAW,GOT,2023-10-09 20:35:00,2023-10-09 22:20:00,0 days 01:45:00,2023-10-13 08:00:00,2023-10-13 09:40:00,0 days 01:40:00,344.86,LOT Polish Airlines,3
235,WAW,GOT,2023-10-10 20:35:00,2023-10-10 22:20:00,0 days 01:45:00,2023-10-13 08:00:00,2023-10-13 09:40:00,0 days 01:40:00,344.86,LOT Polish Airlines,2
238,WAW,GOT,2023-10-11 20:35:00,2023-10-11 22:20:00,0 days 01:45:00,2023-10-13 08:00:00,2023-10-13 09:40:00,0 days 01:40:00,344.86,LOT Polish Airlines,1

In [29]:
# df.to_pickle("./flights.pkl")